export interface Recipe {
  id: number
  title: string
  category: string
  time: string
  servings: number
  difficulty: "Fácil" | "Medio" | "Difícil"
  rating: number
  image: string
  description: string
  tags: string[]
  ingredients: string[]
  instructions: string[]
  nutrition: {
    calories: number
    protein: string
    carbs: string
    fat: string
  }
  author: string
  prepTime: string
  cookTime: string
}

export const categories = [
  { name: "Desayuno", emoji: "🥞", color: "bg-orange-100 text-orange-800" },
  { name: "Almuerzo", emoji: "🍽️", color: "bg-green-100 text-green-800" },
  { name: "Cena", emoji: "🍖", color: "bg-purple-100 text-purple-800" },
  { name: "Postres", emoji: "🍰", color: "bg-pink-100 text-pink-800" },
  { name: "Snacks", emoji: "🍿", color: "bg-yellow-100 text-yellow-800" },
  { name: "Bebidas", emoji: "🥤", color: "bg-blue-100 text-blue-800" },
]

export const recipes: Recipe[] = [
  {
    id: 1,
    title: "Pancakes Esponjosos de Arándanos",
    category: "Desayuno",
    time: "15 min",
    servings: 4,
    difficulty: "Fácil",
    rating: 4.8,
    image: "/placeholder.svg?height=400&width=600",
    description: "Deliciosos pancakes súper esponjosos con arándanos frescos que se derriten en tu boca",
    tags: ["Sin gluten", "Vegetariano", "Rápido"],
    author: "Chef María González",
    prepTime: "5 min",
    cookTime: "10 min",
    ingredients: [
      "2 tazas de harina sin gluten",
      "2 cucharadas de azúcar",
      "2 cucharaditas de polvo de hornear",
      "1/2 cucharadita de sal",
      "2 huevos grandes",
      "1 3/4 tazas de leche",
      "1/4 taza de mantequilla derretida",
      "1 taza de arándanos frescos",
      "Miel o jarabe de maple para servir",
    ],
    instructions: [
      "En un bowl grande, mezcla la harina, azúcar, polvo de hornear y sal.",
      "En otro bowl, bate los huevos, luego añade la leche y mantequilla derretida.",
      "Vierte los ingredientes húmedos sobre los secos y mezcla suavemente hasta que se combinen.",
      "Incorpora delicadamente los arándanos a la mezcla.",
      "Calienta una sartén antiadherente a fuego medio y engrasa ligeramente.",
      "Vierte 1/4 taza de mezcla por cada pancake en la sartén caliente.",
      "Cocina hasta que aparezcan burbujas en la superficie (2-3 min), luego voltea.",
      "Cocina por 1-2 minutos más hasta que estén dorados.",
      "Sirve inmediatamente con miel o jarabe de maple.",
    ],
    nutrition: {
      calories: 285,
      protein: "8g",
      carbs: "45g",
      fat: "9g",
    },
  },
  {
    id: 2,
    title: "Tacos de Pescado Tropical",
    category: "Almuerzo",
    time: "25 min",
    servings: 3,
    difficulty: "Medio",
    rating: 4.9,
    image: "/placeholder.svg?height=400&width=600",
    description: "Tacos frescos con pescado a la plancha y salsa de mango que te transportarán al paraíso",
    tags: ["Saludable", "Picante", "Tropical"],
    author: "Chef Carlos Mendoza",
    prepTime: "15 min",
    cookTime: "10 min",
    ingredients: [
      "500g de filete de pescado blanco",
      "8 tortillas de maíz pequeñas",
      "1 mango maduro cortado en cubitos",
      "1/2 cebolla morada finamente picada",
      "1 jalapeño sin semillas, picado",
      "1/4 taza de cilantro fresco picado",
      "Jugo de 2 limas",
      "2 cucharadas de aceite de oliva",
      "1 cucharadita de comino",
      "Sal y pimienta al gusto",
      "Repollo morado rallado para servir",
    ],
    instructions: [
      "Sazona el pescado con sal, pimienta y comino.",
      "Calienta el aceite en una sartén a fuego medio-alto.",
      "Cocina el pescado 3-4 minutos por lado hasta que esté dorado y se desmenuce fácilmente.",
      "Mientras tanto, mezcla el mango, cebolla, jalapeño, cilantro y jugo de lima para hacer la salsa.",
      "Calienta las tortillas en una sartén seca o comal.",
      "Desmenúza el pescado cocido en trozos grandes.",
      "Arma los tacos colocando pescado en cada tortilla.",
      "Cubre con la salsa de mango y repollo rallado.",
      "Sirve inmediatamente con gajos de lima adicionales.",
    ],
    nutrition: {
      calories: 320,
      protein: "28g",
      carbs: "35g",
      fat: "12g",
    },
  },
  {
    id: 3,
    title: "Brownies de Chocolate Negro",
    category: "Postres",
    time: "45 min",
    servings: 8,
    difficulty: "Fácil",
    rating: 4.7,
    image: "/placeholder.svg?height=400&width=600",
    description: "Brownies súper chocolatosos y húmedos que son absolutamente irresistibles",
    tags: ["Chocolate", "Casero", "Indulgente"],
    author: "Chef Ana Rodríguez",
    prepTime: "15 min",
    cookTime: "30 min",
    ingredients: [
      "200g de chocolate negro (70% cacao)",
      "150g de mantequilla",
      "200g de azúcar morena",
      "3 huevos grandes",
      "1 cucharadita de extracto de vainilla",
      "100g de harina común",
      "30g de cacao en polvo",
      "1/2 cucharadita de sal",
      "100g de nueces picadas (opcional)",
      "Azúcar glass para decorar",
    ],
    instructions: [
      "Precalienta el horno a 180°C y engrasa un molde cuadrado de 20cm.",
      "Derrite el chocolate y mantequilla en baño maría, revolviendo hasta que esté suave.",
      "Retira del fuego y mezcla el azúcar morena hasta incorporar.",
      "Añade los huevos uno a uno, batiendo bien después de cada adición.",
      "Incorpora la vainilla.",
      "En un bowl separado, tamiza la harina, cacao y sal.",
      "Incorpora gradualmente los ingredientes secos a la mezcla de chocolate.",
      "Añade las nueces si las usas.",
      "Vierte en el molde preparado y nivela la superficie.",
      "Hornea 25-30 minutos hasta que un palillo salga con pocas migas húmedas.",
      "Deja enfriar completamente antes de cortar y espolvorea con azúcar glass.",
    ],
    nutrition: {
      calories: 385,
      protein: "6g",
      carbs: "45g",
      fat: "22g",
    },
  },
  {
    id: 4,
    title: "Ensalada Arcoíris Mediterránea",
    category: "Almuerzo",
    time: "10 min",
    servings: 2,
    difficulty: "Fácil",
    rating: 4.6,
    image: "/placeholder.svg?height=400&width=600",
    description: "Ensalada colorida con ingredientes frescos del mediterráneo llena de sabor y nutrientes",
    tags: ["Vegano", "Saludable", "Mediterráneo"],
    author: "Chef Elena Martín",
    prepTime: "10 min",
    cookTime: "0 min",
    ingredients: [
      "4 tazas de mezcla de lechugas",
      "1 pepino cortado en rodajas",
      "2 tomates cherry cortados por la mitad",
      "1/2 pimiento rojo en tiras",
      "1/2 pimiento amarillo en tiras",
      "1/4 taza de aceitunas kalamata",
      "1/4 taza de queso feta desmenuzado",
      "1/4 cebolla morada en rodajas finas",
      "3 cucharadas de aceite de oliva extra virgen",
      "2 cucharadas de vinagre balsámico",
      "1 cucharadita de orégano seco",
      "Sal y pimienta al gusto",
    ],
    instructions: [
      "Lava y seca bien todas las verduras.",
      "En un bowl grande, coloca la mezcla de lechugas como base.",
      "Distribuye uniformemente el pepino, tomates, pimientos y cebolla sobre las lechugas.",
      "Añade las aceitunas y el queso feta por encima.",
      "En un bowl pequeño, mezcla el aceite de oliva, vinagre balsámico, orégano, sal y pimienta.",
      "Bate bien el aderezo hasta que esté emulsionado.",
      "Rocía el aderezo sobre la ensalada justo antes de servir.",
      "Mezcla suavemente y sirve inmediatamente.",
    ],
    nutrition: {
      calories: 245,
      protein: "8g",
      carbs: "15g",
      fat: "18g",
    },
  },
  {
    id: 5,
    title: "Smoothie Bowl Tropical",
    category: "Desayuno",
    time: "8 min",
    servings: 1,
    difficulty: "Fácil",
    rating: 4.9,
    image: "/placeholder.svg?height=400&width=600",
    description: "Bowl cremoso con frutas tropicales y toppings crujientes para empezar el día con energía",
    tags: ["Vegano", "Saludable", "Tropical"],
    author: "Chef Sofia López",
    prepTime: "8 min",
    cookTime: "0 min",
    ingredients: [
      "1 plátano congelado",
      "1/2 taza de mango congelado",
      "1/2 taza de piña congelada",
      "1/4 taza de leche de coco",
      "1 cucharada de miel o jarabe de agave",
      "1/4 taza de granola",
      "2 cucharadas de coco rallado",
      "1 kiwi en rodajas",
      "1/4 taza de arándanos frescos",
      "1 cucharada de semillas de chía",
      "Hojas de menta para decorar",
    ],
    instructions: [
      "En una licuadora potente, combina el plátano, mango y piña congelados.",
      "Añade la leche de coco y miel, licúa hasta obtener una consistencia cremosa y espesa.",
      "Si está muy espeso, añade un poco más de leche de coco gradualmente.",
      "Vierte la mezcla en un bowl.",
      "Decora con granola, coco rallado, rodajas de kiwi y arándanos.",
      "Espolvorea las semillas de chía por encima.",
      "Decora con hojas de menta fresca.",
      "Sirve inmediatamente con una cuchara.",
    ],
    nutrition: {
      calories: 420,
      protein: "8g",
      carbs: "78g",
      fat: "12g",
    },
  },
  {
    id: 6,
    title: "Pizza Margarita Casera",
    category: "Cena",
    time: "35 min",
    servings: 4,
    difficulty: "Medio",
    rating: 4.8,
    image: "/placeholder.svg?height=400&width=600",
    description: "Pizza clásica con masa casera y ingredientes frescos que rivaliza con las mejores pizzerías",
    tags: ["Vegetariano", "Casero", "Italiano"],
    author: "Chef Marco Rossi",
    prepTime: "20 min",
    cookTime: "15 min",
    ingredients: [
      "300g de harina de fuerza",
      "200ml de agua tibia",
      "1 cucharadita de levadura seca",
      "1 cucharadita de azúcar",
      "2 cucharadas de aceite de oliva",
      "1 cucharadita de sal",
      "200g de salsa de tomate para pizza",
      "250g de mozzarella fresca en rodajas",
      "Hojas de albahaca fresca",
      "Aceite de oliva extra virgen",
      "Sal y pimienta al gusto",
    ],
    instructions: [
      "Disuelve la levadura y azúcar en agua tibia, deja reposar 5 minutos hasta que haga espuma.",
      "En un bowl grande, mezcla la harina y sal, haz un hueco en el centro.",
      "Vierte la mezcla de levadura y aceite de oliva, mezcla hasta formar una masa.",
      "Amasa en una superficie enharinada por 8-10 minutos hasta que esté suave y elástica.",
      "Coloca en un bowl engrasado, cubre y deja reposar 1 hora hasta que duplique su tamaño.",
      "Precalienta el horno a 250°C con una piedra para pizza si tienes.",
      "Estira la masa en una superficie enharinada hasta formar un círculo de 30cm.",
      "Transfiere a una bandeja para pizza o papel pergamino.",
      "Extiende la salsa de tomate dejando un borde de 2cm.",
      "Distribuye la mozzarella uniformemente y sazona con sal y pimienta.",
      "Hornea 12-15 minutos hasta que los bordes estén dorados y el queso burbujee.",
      "Retira del horno, añade hojas de albahaca fresca y rocía con aceite de oliva.",
      "Deja reposar 2-3 minutos antes de cortar y servir.",
    ],
    nutrition: {
      calories: 485,
      protein: "22g",
      carbs: "58g",
      fat: "18g",
    },
  },
]
